### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minseongg** [minseongg/fluid#1]
## TODO List

- [ ] ko2en에서 단어 단위로 첫 번째 글자는 보여주기
- [ ] 하나의 묶음을 끝냈을 때 맞은 개수, 틀린 단어들 정리해서 보여주는 화면 추가
- [ ] 하나의 묶음에 대해 단어들이 셔플된 후 나오게 하기
- [ ] 하다가 중간에 나갈 수 있게 하기
